services:
  # PostgreSQL 데이터베이스
  # AutoDev 서버는 호스트에서 직접 실행됩니다
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: autodev
      POSTGRES_USER: autodev
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # 호스트에서 접근 가능
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autodev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: